name: Java CI

on: [push]

jobs:
  build:
 
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Ant
      run: ant -noinput -buildfile build.xml
    - name: Release
      uses: softprops/action-gh-release@v1
      if: startsWith(github.ref, 'refs/tags/')
      with:
        files: |
          dist/mhsig
          dist/mhsig*jar
      env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    - name: Upload mhsig executable JAR
      uses: actions/upload-artifact@v4
      with:
        name: mhsig
        path: dist/mhsig

    - name: Upload mhsig JAR
      uses: actions/upload-artifact@v4
      with:
        name: mhsig.jar
        path: dist/mhsig*.jar
